export const meta = {
  name: 'concept-build',
  description: 'One concept: typography + image art direction, then 3D/WebGL + motion direction, then five creative-developer passes with render-and-look self-QA',
  phases: [
    { title: 'Typography+Imagery', detail: 'type system and procedural/processed imagery, in parallel' },
    { title: '3D+Motion', detail: '3D/WebGL director decides & builds, motion director writes the language' },
    { title: 'Develop', detail: 'scaffold+opening, scenes 2-3, scenes 4-6, mobile re-art-direction, integration polish' },
  ],
}

const ROOT = '/home/user/htmlcourse'
const C = args // { nn, dirName, slug, name, url, category, revision? }
const DIR = `${ROOT}/concepts/${C.dirName}`
const DEV_PORT = 5100 + parseInt(C.nn, 10)
const QA_PORT = 5200 + parseInt(C.nn, 10)

const PRE = `You are a specialist in a design swarm building ten award-level, standalone website redesigns of real brands (independent speculative concepts for a designer's portfolio; the target is Awwwards/FWA/CSSDA calibre, NOT a template). FIRST read ${ROOT}/00_GLOBAL/SWARM_PROTOCOL.md completely, and the sections of ${ROOT}/00_GLOBAL/BRIEF.md relevant to your role. Your concept: #${C.nn} ${C.name} (${C.url}), category ${C.category}. Your concept directory (the ONLY place you write): ${DIR}. Read, in this order: ${DIR}/DIRECTION.md (the LOCKED creative plan — execute it faithfully; if you believe it is flawed, write the issue in ${DIR}/REVISION_LOG.md and execute the closest sound interpretation rather than silently diverging), BRIEF.md (lane), BRAND.md, ASSET_SOURCES.md + ASSET_MANIFEST.md, REFERENCES.md, REFERENCE_DNA.md, and any existing TYPOGRAPHY.md / MOTION.md / TECH.md / STATUS.md / REVISION_LOG.md. Dev port ${DEV_PORT}, QA/preview port ${QA_PORT}.${C.revision ? '\nDIVERSITY-GATE REVISION IN FORCE (already folded into DIRECTION.md; respect it): ' + C.revision : ''}`

const HAND = `Finish with a handoff (DECISION / WHY / FILES / OPEN ISSUES / NEXT ACTION, ≤200 words) — detail lives in the files. Be honest about anything unfinished, unverified, or temporary.`

const typographyPrompt = () => `${PRE}
ROLE: TYPOGRAPHY DIRECTOR. Typography is one of the most important parts of this project. Read BRIEF "TYPOGRAPHY FREEDOM" and SWARM_PROTOCOL hard rule 4.
1. Identify the real fonts of the primary references (inspect.json files in ${ROOT}/00_GLOBAL/REFERENCE_LIBRARY/<slug>/, network font file names, @font-face rules) and the brand's own typeface identity (BRAND.md). Name them honestly even when you cannot ship them.
2. Shortlist 3 candidate pairings per role (display / text / ui / numerals) that are LEGAL to ship (Google Fonts via npm @fontsource/@fontsource-variable, Fontshare, Velvetyne, Open Foundry, Collletttivo, other clearly-licensed open fonts; verify each licence). Match character, width, contrast, x-height, weight, proportions and attitude of what the direction needs. Do not default to Inter/Roboto/Arial/Manrope/Space Grotesk/Poppins unless you can argue for it from the design — convenience is not an argument.
3. TEST IN THE BROWSER: build a throwaway specimen page in ${DIR}/_work/type-specimen/ using the project's real palette and real headline/body/button/nav copy from DIRECTION.md/BRAND.md COPY BANK at desktop (1440) and mobile (390) widths, serve it (node ${ROOT}/_tools/serve.mjs ${DIR}/_work/type-specimen ${DEV_PORT}) and capture with node ${ROOT}/_tools/shoot.mjs --url http://127.0.0.1:${DEV_PORT} --out ${DIR}/_work/type-shots --viewports desktop,mobile. LOOK at the screenshots (Read tool). Judge headline breaks, optical sizing, tracking, leading, x-height, numerals, paragraph measure, mobile wrapping, button/nav labels; put the reference's typography next to yours (node ${ROOT}/_tools/compare.mjs). Iterate until it is genuinely memorable, not merely correct. Kill the server when done.
4. Deliver: font files (woff2, subset sensibly, variable where it helps) in ${DIR}/assets/fonts/; ${DIR}/assets/fonts/fonts.css with @font-face (font-display: swap) AND metric-matched fallback faces (size-adjust / ascent-override / descent-override / line-gap-override) so there is no layout jump; ${DIR}/TYPOGRAPHY.md: roles, families, licence + source links, the original reference fonts and why each alternative was chosen, fluid scale as CSS custom properties with clamp() for desktop and mobile, leading/tracking/measure rules, OpenType features, headline line-break rules (text-wrap, manual breaks) for the real headlines, and what NOT to do. Add each font to ${DIR}/ASSET_MANIFEST.md with licence. ${HAND}`

const imageryPrompt = () => `${PRE}
ROLE: IMAGE ART DIRECTOR. Read BRIEF "GENERATED ASSET WORKFLOW", "BRAND ASSET RULE", "REAL BRAND ASSETS". There is NO text-to-image model here: your craft is art-directing and PRODUCING imagery computationally and from real material — processing official photography (crop, grade, composite, cut-out with clean edges, duotone/halftone/print treatments where they are the concept), procedural textures and backgrounds (Python numpy/OpenCV/Pillow/skimage via ${ROOT}/_tools/.venv/bin/python -I; GLSL/canvas/Three.js rendered through Chromium; SVG; ImageMagick; ffmpeg loops), shader-support maps (displacement, alpha, normal, roughness), environment maps. Generated imagery complements real brand material; it never replaces beautiful official photography, and it must never look like AI filler or stock.
1. From DIRECTION.md list EVERY image/texture/video each scene needs, desktop AND mobile crop. For each: use a real asset (name it) or write a generated-asset spec in ${DIR}/ASSET_SOURCES.md FIRST with every field: purpose, dimensions/aspect, composition, subject, product placement, camera position, focal length, crop, lighting, material behaviour, shadows, environment, background, visual texture, negative space, typography-safe area, mobile crop, prohibited elements. No vague specs.
2. Produce the assets into ${DIR}/assets/{images,generated,textures,video} (optimised: WebP/AVIF/JPEG ~q80, ≤2400px wide, transparent PNG/WebP only where alpha is required, short compressed loops only; per-file ≤25 MB, total budget ≈80 MB with what the Asset Hunter already placed). Keep sources/scripts in ${DIR}/_work (gitignored) — but also keep the generator scripts that produced final assets in ${DIR}/assets/generated/_src/ so the work is reproducible.
3. VERIFY IN CONTEXT: build contact sheets (ImageMagick montage) and, where scenes already exist, look at them in situ; iterate until each asset fits the site's art direction (colour, contrast, crop, typography-safe area, mobile crop). Cut-outs: inspect edges at 400% for halos/fringing.
4. Update ${DIR}/ASSET_MANIFEST.md (every file: role, source, original/generated, licence/status, optimisation, final/temporary — mark anything not yet final as temporary). If a scene needs an asset you cannot produce at quality, write it to ${DIR}/NEEDS.md with a proposed re-plan; do not ship a bad stand-in. ${HAND}`

const threeDPrompt = () => `${PRE}
ROLE: 3D / WEBGL DIRECTOR. Read BRIEF "3D / WEBGL / THREE.JS", "3D ASSET QUALITY", "3D ASSET WORKFLOW", "3D MODEL QUALITY", "3D / WEBGL REVIEW". First DECIDE, from DIRECTION.md's tech plan, whether 3D/WebGL (product model, image/liquid shaders, environment, typographic depth…) materially improves THIS concept. 3D is not automatically good; a sophisticated typography-led site without 3D beats bad 3D. If DIRECTION.md calls for no 3D/WebGL, write 'TECH.md → 3D/WebGL: none — <reason>' and stop (the developers will handle DOM/CSS/canvas-2D needs).
If YES:
1. MODEL/SCENE: use an official or legitimately-licensed model from ${DIR}/assets/3d if the Asset Hunter found one; otherwise MODEL/RECONSTRUCT a high-quality approximation using the official photography as exact reference (Three.js parametric geometry: Lathe/Extrude/custom BufferGeometry, bevels, correct proportions, real branding via textures/decals from the official assets; PBR materials with generated roughness/normal maps; environment lighting — procedural, or CC0 HDRIs from polyhaven.com (open) converted to a small .hdr/.exr/.jpg). Never ship visibly cheap geometry for a recognisable product. Compare renders against the official packshots at the same camera angle, side by side, and iterate until fidelity is convincing.
2. BUILD a self-contained module in ${DIR}/src/gl/ with a clean API (init(canvas|container, options), setProgress/setState, resize, dispose, fallback poster path) — the Creative Developers will wire it into scroll/interaction. Plus a standalone test harness page in ${DIR}/gl-test/ (own tiny Vite entry or static page + importmap against local three from node_modules) where you can render stills at defined camera positions/states. You may create ${DIR}/package.json if absent (name, "type":"module", scripts dev/build/preview using vite on port ${DEV_PORT}, deps: three + vite) — the developers will extend it. Install with node ${ROOT}/_tools/slot.mjs npm 2 -- npm install.
3. JUDGE WITH YOUR EYES: capture with shoot.mjs (software WebGL is slow but correct), look at the stills: are materials believable, is the lighting considered, does the camera feel authored, does the model look expensive, would the site be stronger without it? Redesign or remove if weak.
4. OPTIMISE: GLB via ${ROOT}/_tools/optimize-glb.sh (meshopt/draco + WebP textures; KTX2 unavailable) into ${DIR}/assets/3d; bundle any decoders locally (copy into public/). Mobile: DPR cap, simplified materials/shadows or a pre-rendered image-sequence/video interpretation; WebGL-context-failure fallback to a designed poster. Respect prefers-reduced-motion.
5. Write ${DIR}/TECH.md (architecture, API, performance budget, mobile interpretation, fallbacks, what the developers must wire and where) and update ${DIR}/ASSET_MANIFEST.md. ${HAND}`

const motionPrompt = () => `${PRE}
ROLE: MOTION DIRECTOR. Read BRIEF "MOTION REVIEW" and DIRECTION.md's motion personality. Design a motion language for THIS concept — not a generic GSAP default. Write ${DIR}/MOTION.md with: the concept's motion principles; a named easing/duration vocabulary (exact cubic-béziers or GSAP eases and ms); the scroll model and, per scene, the choreography (what maps to scroll progress, pin lengths, what is time-based vs scroll-scrubbed); cursor behaviour (only if it has purpose); hover/focus/active states for every control type; navigation open/close; scene/page transitions; the loader/intro as a millisecond storyboard of the first 3 seconds; the ONE signature moment as a storyboard; micro-interactions; reduced-motion equivalents (coherent, not just 'off'); touch/mobile equivalents; performance rules (transform/opacity, will-change discipline, rAF budget). Choose the engine(s) deliberately (native CSS scroll-driven animation / GSAP+ScrollTrigger / Lenis / Motion / none) and justify — not every site gets Lenis+GSAP. Verify package names and CURRENT versions with npm view before listing dependencies. Reject: identical reveals everywhere, fade-up on every section, gratuitous parallax, endless smooth-scroll gimmicks, motion masking weak layout, animation on every object. Observe the references' real behaviour from their screenshots/timeline frames and REF.md notes to ground your choices. ${HAND}`

const DEV_PREFACE = `ROLE: CREATIVE DEVELOPER. You implement the approved art direction to a standard that would sit beside Awwwards/FWA work. Craft rules: Vite project in ${DIR} (package.json scripts dev = vite --host 127.0.0.1 --port ${DEV_PORT}, build, preview); choose dependencies per MOTION.md/TECH.md/DIRECTION.md (verify versions with npm view; install via node ${ROOT}/_tools/slot.mjs npm 2 -- npm install ...); vanilla/TS/framework as the concept needs — no framework by default, no Tailwind/shadcn look. EVERYTHING local at runtime (fonts from assets/fonts, images, models, decoders) — no CDN/hotlinks; the site works offline after install. Real copy only (BRAND.md COPY BANK, real product facts with sources; creative headlines in the brand's voice; no lorem, no invented facts/metrics/testimonials). Semantic HTML, one h1, visible focus, 4.5:1 text contrast, ≥44px primary touch targets, no horizontal overflow, fluid type from TYPOGRAPHY.md tokens, 100svh/dvh handled, prefers-reduced-motion coherent. Footer includes the colophon line from SWARM_PROTOCOL rule 9. External links go to real brand URLs (target=_blank rel=noopener). No dead buttons in visible states: product/variant selection, nav, galleries, cart-like interactions, audio/3D controls must behave convincingly.
SELF-QA IS PART OF THE JOB: after implementing, render and LOOK. Run ${ROOT}/_tools/qa.sh ${DIR} <round> --viewports desktop,mobile --steps 14 [--script ${DIR}/qa-states.mjs] (builds, serves dist on ${QA_PORT}, captures intro timeline + scroll journey + interaction states + report.json), open the contact sheets and individual frames with the Read tool, read report.json (console errors, failed requests, overflow offenders, font check, tap targets, placeholder text) and fix everything real before you hand off. A passing build proves nothing about design. Compare against the references' screenshots when judging quality (node ${ROOT}/_tools/compare.mjs). Keep a script ${DIR}/qa-states.mjs (export default async (page,{shot,sleep,vp}) => {...}) that drives the key interactions (hover/click/drag/select/open nav) so later QA rounds can capture those states.
Append what you did and any deviations to ${DIR}/REVISION_LOG.md and update ${DIR}/STATUS.md and TECH.md. Do not leave dev servers running. Do not run git.`

const devPass = (n, scope) => `${PRE}
${DEV_PREFACE}
THIS IS DEVELOPER PASS ${n} OF 5. SCOPE: ${scope}
Read what earlier passes built (src/, STATUS.md, REVISION_LOG.md) and extend it coherently; do not rewrite earlier work without a reason you log. ${HAND}`

phase('Typography+Imagery')
await parallel([
  () => agent(typographyPrompt(), { label: `typography:${C.slug}`, phase: 'Typography+Imagery' }),
  () => agent(imageryPrompt(), { label: `imagery:${C.slug}`, phase: 'Typography+Imagery' }),
])

phase('3D+Motion')
await parallel([
  () => agent(threeDPrompt(), { label: `3d:${C.slug}`, phase: '3D+Motion' }),
  () => agent(motionPrompt(), { label: `motion:${C.slug}`, phase: '3D+Motion' }),
])

phase('Develop')
await agent(devPass(1, `Scaffold the project (package.json, vite config, index.html, base CSS architecture and design tokens from TYPOGRAPHY.md + palette in DIRECTION.md, font loading via assets/fonts/fonts.css, scroll/motion engine setup per MOTION.md, global layout, NAVIGATION as designed, the loader/intro sequence as storyboarded) and build SCENE 1 — the unforgettable opening — to final quality, desktop and mobile. If TECH.md describes a src/gl module, integrate it. Add a stub footer with the colophon.`), { label: `dev1:${C.slug}`, phase: 'Develop' })
await agent(devPass(2, `Build SCENES 2 and 3 of DIRECTION.md to final quality (desktop and mobile), including their interactions and assets.`), { label: `dev2:${C.slug}`, phase: 'Develop' })
await agent(devPass(3, `Build the REMAINING SCENES (4 onward) of DIRECTION.md to final quality (desktop and mobile), including any functional commerce/product/gallery/audio interactions and the real footer + colophon + real external links. Every scene must be as strong as scene 1: sections 2–6 are where weak sites hide.`), { label: `dev3:${C.slug}`, phase: 'Develop' })
await agent(devPass(4, `MOBILE RE-ART-DIRECTION. Mobile is not flex-direction: column. Re-compose each scene for 390×844, 360×740 and tablet 820×1180: typography scale and line breaks, image crops/focal points, section order and whitespace, navigation, WebGL camera/product placement (or an intentional pre-rendered/2D interpretation), motion and touch behaviour, tap targets. Capture and LOOK at every mobile frame; fix until the mobile version feels designed for the phone and keeps the best part of the desktop idea.`), { label: `dev4:${C.slug}`, phase: 'Develop' })
await agent(devPass(5, `INTEGRATION & POLISH: coherence between scenes; transitions and states; hover/focus/active; keyboard path; reduced-motion path; loading states; image/model lazy-loading; error/fallback states; zero console errors and failed requests; no placeholder/temporary assets (update ASSET_MANIFEST.md: everything final); fonts verifiably rendering; no horizontal overflow at 320/360/390/430/768/1024/1280/1440/1920; verify 'npm install && npm run dev' and 'npm run build' work from a clean checkout of this folder (delete node_modules and reinstall once); finish qa-states.mjs; update TECH.md/STATUS.md with the run instructions. Then self-review the whole rendered site against DIRECTION.md's acceptance criteria and the references, list remaining weaknesses honestly in STATUS.md OPEN DEFECTS and fix the ones you can.`), { label: `dev5:${C.slug}`, phase: 'Develop' })

return { concept: C.dirName, built: true }
